/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import static Home.measurements.mob;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyEvent;

/**
 *
 * @author jameel
 */
public class member extends javax.swing.JFrame {

    /**
     * Creates new form member
     */
    public member() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        memname = new javax.swing.JTextField();
        mempass = new javax.swing.JTextField();
        memmob = new javax.swing.JTextField();
        memuser = new javax.swing.JTextField();
        memreg = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        memname.setBackground(new java.awt.Color(81, 79, 79));
        memname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memname.setForeground(new java.awt.Color(255, 153, 153));
        memname.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memname.setText("Enter Full Name");
        memname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        memname.setCaretColor(new java.awt.Color(255, 0, 0));
        memname.setName("user"); // NOI18N
        memname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memnameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memnameFocusLost(evt);
            }
        });

        mempass.setBackground(new java.awt.Color(81, 79, 79));
        mempass.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mempass.setForeground(new java.awt.Color(255, 153, 153));
        mempass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mempass.setText("Enter Password");
        mempass.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        mempass.setCaretColor(new java.awt.Color(255, 0, 0));
        mempass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mempassFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                mempassFocusLost(evt);
            }
        });

        memmob.setBackground(new java.awt.Color(81, 79, 79));
        memmob.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memmob.setForeground(new java.awt.Color(255, 153, 153));
        memmob.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memmob.setText("Enter Contact No.");
        memmob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        memmob.setCaretColor(new java.awt.Color(255, 0, 0));
        memmob.setName("user"); // NOI18N
        memmob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memmobFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memmobFocusLost(evt);
            }
        });
        memmob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                memmobKeyPressed(evt);
            }
        });

        memuser.setBackground(new java.awt.Color(81, 79, 79));
        memuser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memuser.setForeground(new java.awt.Color(255, 153, 153));
        memuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        memuser.setText("Enter Username");
        memuser.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        memuser.setCaretColor(new java.awt.Color(255, 0, 0));
        memuser.setName("user"); // NOI18N
        memuser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                memuserFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                memuserFocusLost(evt);
            }
        });

        memreg.setBackground(new java.awt.Color(81, 79, 79));
        memreg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        memreg.setForeground(new java.awt.Color(255, 51, 51));
        memreg.setText("Register");
        memreg.setBorder(null);
        memreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memregActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CITY JEANS");
        jLabel1.setNextFocusableComponent(memname);

        close.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 255, 255));
        close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        close.setText("X");
        close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memname)
                    .addComponent(mempass)
                    .addComponent(memmob, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(memuser, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
                    .addComponent(memreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(memname, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(memuser, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(memmob, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(mempass, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(memreg, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void memnameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memnameFocusGained
        // TODO add your handling code here:
        memname.setText("");
        memname.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_memnameFocusGained

    private void memnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memnameFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_memnameFocusLost

    private void mempassFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mempassFocusGained
        // TODO add your handling code here:
        mempass.setText("");
        mempass.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_mempassFocusGained

    private void mempassFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mempassFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_mempassFocusLost

    private void memmobFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memmobFocusGained
        // TODO add your handling code here:
        memmob.setText("");
        memmob.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_memmobFocusGained

    private void memmobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memmobFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_memmobFocusLost

    private void memuserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memuserFocusGained
        // TODO add your handling code here:
        memuser.setText("");
        memuser.setForeground(new Color(255,51,51));
    }//GEN-LAST:event_memuserFocusGained

    private void memuserFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_memuserFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_memuserFocusLost

    private void memregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memregActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://www.remotemysql.com:3306/rVPGwzQ1zC", "rVPGwzQ1zC", "uMcb3Rj2Qn");

            String sql = "insert into members values(?,?,?,?)";
            
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, memname.getText());
            ps.setString(2, memuser.getText());
            ps.setString(3, memmob.getText());
            ps.setString(4, mempass.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "You have successfully registered", "City Jeans", JOptionPane.PLAIN_MESSAGE);
            con.close();
            
            new memberLogin().setVisible(true);
            dispose();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_memregActionPerformed

    private void memmobKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_memmobKeyPressed
        // TODO add your handling code here:
        String phoneNumber = mob.getText();
        int numlen = phoneNumber.length();
        char ch = evt.getKeyChar();
        
        if(evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9'){
            if(numlen < 10){
                memmob.setEditable(true);
            }
            else{
                memmob.setEditable(false);
            }
        }
        else{
            if(evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE || evt.getExtendedKeyCode() == KeyEvent.VK_DELETE){
                memmob.setEditable(true);
            }
            else{
                memmob.setEditable(false);
            }
        }
    }//GEN-LAST:event_memmobKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel close;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField memmob;
    private javax.swing.JTextField memname;
    private javax.swing.JTextField mempass;
    private javax.swing.JButton memreg;
    private javax.swing.JTextField memuser;
    // End of variables declaration//GEN-END:variables
}
